WhenWillDaddyBeHome/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using WhenWillDaddyBeHome.Areas.HelpPage.ModelDescriptions;

namespace WhenWillDaddyBeHome.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

WhenWillDaddyBeHome/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WhenWillDaddyBeHome.Models
{
    public class Location
    {
        public Guid Id { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        public double TimestampUTC { get; set; }
    }
}

WhenWillDaddyBeHome/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WhenWillDaddyBeHome.Areas.HelpPage.ModelDescriptions;
using WhenWillDaddyBeHome.Areas.HelpPage.Models;

namespace WhenWillDaddyBeHome.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WhenWillDaddyBeHome/Controllers/AController.cs
using Microsoft.AspNet.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WhenWillDaddyBeHome.Hubs;
using WhenWillDaddyBeHome.Models;
using System.Web.Caching;

namespace WhenWillDaddyBeHome.Controllers
{
    public class AController : Controller
    {
        [HttpGet]
        public ActionResult GetNewToken()
        {
            //return a unique token that is meaningless unless someone is listening on it
            return Json(Guid.NewGuid(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public void UpdateMyLocation(Location value)
        {
            value.TimestampUTC = DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds;
            if (HttpContext.Cache[value.Id.ToString()] != null)
            {
                HttpContext.Cache.Remove(value.Id.ToString());
            }
			Request.RequestContext.HttpContext.Cache.Add(value.Id.ToString(), value, null, Cache.NoAbsoluteExpiration, Cache.NoSlidingExpiration, CacheItemPriority.Default, null);

            var hubContext = GlobalHost.ConnectionManager.GetHubContext<LocationHub>();
            hubContext.Clients.All.locationMessageReceived(value.Id, 
                value.Lat, 
                value.Long, 
                value.TimestampUTC);
        }
    }
}

WhenWillDaddyBeHome/Controllers/WhereIsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WhenWillDaddyBeHome.Models;

namespace WhenWillDaddyBeHome.Controllers
{
    public class WhereIsController : Controller
    {
        public ActionResult Daddy(Guid? id)
        {
			var cachedToken = Request.RequestContext.HttpContext.Cache[id.GetValueOrDefault().ToString()] as Location;
			return View(cachedToken);
        }

        public ActionResult Here(Guid id)
        {
            return View(id);
        }
    }
}

WhenWillDaddyBeHome/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>

WhenWillDaddyBeHome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WhenWillDaddyBeHome/Views/WhereIs/Daddy.cshtml
@model WhenWillDaddyBeHome.Models.Location
@{
    ViewBag.Title = "Daddy";
    var trackingToken = "";
}

<h2>When will Daddy be home?</h2>

@if (Model == null)
{
    var newToken = Guid.NewGuid();
    @Html.ActionLink("Get a new tracking token", "Here", new { id = newToken })
}
else {
    trackingToken = Model.Id.ToString();
    <div id="map" style="height:300px;"></div>
    <p id="current"></p>
}

@section Scripts{
    <script src="~/signalr/hubs"></script>

<script 
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARyjD48pzEQIPETramNz7ZxtvgEEpuw5Y&signed_in=true">
</script>

    <script type="text/javascript">
        //from https://github.com/SignalR/Samples/blob/master/Samples_2.1.0/WebApplication/Features/Hub/DemoHub.js

        var map = undefined;
        var geocoder = new google.maps.Geocoder;

        function initMap(lat, long, timestampUTC) {
            var myLatLng = { lat: lat, lng: long };

            if (map === undefined) {
                map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 14,
                    center: myLatLng
                });
            }

            var address = 'somewhere';
            geocoder.geocode({ 'location': myLatLng }, function (results, status) {
                if (status === google.maps.GeocoderStatus.OK) {
                    if (results[1]) {
                        address = results[1].formatted_address;
                    }
                }
            });

            var currentLocation = 'Daddy was at ' + address + ' at ' + (new Date(timestampUTC)).toString() + 'UTC';

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                title: currentLocation
            });

            $("#current").html(currentLocation);
        }

        var locationHub = $.connection.locationHub;

        locationHub.client.locationMessageReceived = function (token, lat, long, timestampUTC) {
            if (token === '@trackingToken') {
                //message was for me, update the map
                initMap(lat, long, timestampUTC);
                console.log(lat);
                console.log(long);
            }
        };

        $.connection.hub.start();

        @if(Model != null)
        {
            @:initMap(@Model.Lat, @Model.Long, @Model.TimestampUTC);
        }

    </script>

   
}

WhenWillDaddyBeHome/Views/WhereIs/Here.cshtml
@model Guid
@{
    ViewBag.Title = "Here";
}

<h2>I am here!</h2>

<div id="map" style="height:300px;"></div>

@*<p>Share this location</p>*@

@section Scripts{

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARyjD48pzEQIPETramNz7ZxtvgEEpuw5Y&signed_in=true">
    </script>


    <script type="text/javascript">

        var map = undefined;

        function getLocation(timeout) {
            window.setTimeout(function () {
                var position = navigator.geolocation.getCurrentPosition(updateLocation);
            }, timeout);
        }

        function updateLocation(position) {
            var lat = position.coords.latitude;
            var long = position.coords.longitude;
            initMap(lat, long);
            $.post('@Url.Action("UpdateMyLocation", "A")', {
                Id: '@Model',
                Lat: lat,
                Long: long
            }, function () {
                getLocation(60000);
            });
        }

        function initMap(lat, long) {
            var myLatLng = { lat: lat, lng: long };

            if (map === undefined) {
                map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 14,
                    center: myLatLng
                });
            }

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                title: 'Here!'
            });

        }

        getLocation(1);

    </script>
}